# Generated by Django 6.0 on 2026-01-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('partner_type', models.CharField(choices=[('entreprise', 'Entreprise'), ('universite', 'Université'), ('institution', 'Institution'), ('ong', 'ONG')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('en_discussion', 'En discussion'), ('inactif', 'Inactif')], default='en_discussion', max_length=20, verbose_name='Statut')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Personne de contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget alloué')),
                ('consumed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget consommé')),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='core.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('doc_type', models.CharField(choices=[('contrat', 'Contrat'), ('budget', 'Budget'), ('rapport', 'Rapport'), ('note', 'Note')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('a_signer', 'À signer'), ('a_valider', 'À valider'), ('signe', 'Signé')], default='a_valider', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('created_by', models.CharField(max_length=100, verbose_name='Créé par')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('due_date', models.DateField(verbose_name='Date limite')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Date de signature')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle')),
                ('workload', models.IntegerField(default=0, verbose_name='Charge de travail (%)')),
                ('skills', models.TextField(blank=True, verbose_name='Compétences')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('event_type', models.CharField(choices=[('reunion', 'Réunion'), ('evenement', 'Événement'), ('deadline', 'Deadline')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('duration', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('participants', models.ManyToManyField(related_name='events', to='core.direction', verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_retard', 'En retard')], default='planifie', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('progress', models.IntegerField(default=0, verbose_name='Progression (%)')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget alloué')),
                ('budget_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget consommé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('manager', models.CharField(max_length=100, verbose_name='Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du jalon')),
                ('completed', models.BooleanField(default=False, verbose_name='Complété')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Jalon',
                'verbose_name_plural': 'Jalons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_by', models.CharField(max_length=100, verbose_name='Créé par')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
