# Generated by Django 4.2.11 on 2026-10-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_directions_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='none', max_length=10, verbose_name='Récurrence'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de la récurrence'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_exceptions',
            field=models.JSONField(blank=True, default=list, verbose_name='Exceptions de récurrence'),
        ),
    ]
