# Generated by Django 4.2.11 on 2026-10-08 16:34

from datetime import datetime, timezone as dt_timezone
from decimal import Decimal

from django.db import migrations, models

# Taux 2024 de l'ancien core.currencies.EXCHANGE_RATES (par USD) — utilisés ici
# uniquement pour convertir en GNF d'éventuelles lignes historiques hors GNF/USD.
LEGACY_USD_RATES = {
    'USD': 1.0, 'EUR': 0.92, 'GBP': 0.79, 'JPY': 149.50, 'CNY': 7.24, 'CAD': 1.36,
    'AUD': 1.53, 'CHF': 0.88, 'GNF': 8655.0, 'XOF': 606.0, 'XAF': 606.0, 'NGN': 772.0,
    'ZAR': 18.85, 'EGP': 31.0, 'MAD': 10.05, 'TND': 3.12, 'DZD': 136.5, 'KES': 151.5,
    'GHS': 12.15, 'ETB': 56.5, 'TZS': 2475.0, 'UGX': 3765.0, 'RWF': 1315.0, 'MUR': 45.5,
    'SLL': 22775.0, 'LRD': 191.5, 'GMD': 64.5, 'CVE': 102.5, 'MZN': 64.05, 'AOA': 826.5,
    'ZMW': 24.85, 'BWP': 13.55, 'NAD': 18.85, 'SZL': 18.85, 'LSL': 18.85, 'MWK': 1735.0,
    'ZWL': 3619.0, 'SDG': 602.5, 'LYD': 4.86, 'MRU': 39.5, 'SCR': 45.5, 'DJF': 177.5,
    'KMF': 453.0, 'ERN': 15.0, 'SOS': 570.0, 'SSP': 185.5, 'STN': 22.65, 'BIF': 2855.0,
    'CDF': 2725.0, 'MGA': 4565.0, 'MXN': 17.15, 'GTQ': 7.82, 'HNL': 24.65, 'NIO': 36.85,
    'CRC': 543.5, 'PAB': 1.0, 'DOP': 56.85, 'CUP': 24.0, 'JMD': 155.5, 'HTG': 132.5,
    'TTD': 6.75, 'BBD': 2.0, 'BSD': 1.0, 'BZD': 2.0, 'XCD': 2.7, 'AWG': 1.8, 'ANG': 1.79,
    'KYD': 0.83, 'BRL': 4.95, 'ARS': 835.5, 'CLP': 915.5, 'COP': 3925.0, 'PEN': 3.75,
    'VES': 3619250.0, 'UYU': 38.85, 'PYG': 7325.0, 'BOB': 6.95, 'GYD': 209.5, 'SRD': 34.65,
    'FKP': 0.79, 'NOK': 10.65, 'SEK': 10.85, 'DKK': 6.85, 'PLN': 3.95, 'CZK': 22.85,
    'HUF': 355.5, 'RON': 4.62, 'BGN': 1.8, 'HRK': 7.15, 'RSD': 107.5, 'UAH': 39.15,
    'RUB': 89.5, 'BYN': 3.25, 'MDL': 17.85, 'ALL': 94.5, 'MKD': 56.5, 'BAM': 1.8,
    'ISK': 137.5, 'TRY': 31.5, 'GEL': 2.75, 'AMD': 387.5, 'AZN': 1.7, 'AED': 3.67,
    'SAR': 3.75, 'QAR': 3.64, 'KWD': 0.31, 'BHD': 0.38, 'OMR': 0.38, 'JOD': 0.71,
    'LBP': 89500.0, 'SYP': 12950.0, 'IQD': 1315.0, 'IRR': 42250.0, 'YER': 250.5,
    'ILS': 3.65, 'KRW': 1315.0, 'INR': 83.15, 'IDR': 15650.0, 'MYR': 4.65, 'SGD': 1.34,
    'THB': 35.85, 'VND': 24450.0, 'PHP': 56.5, 'PKR': 279.5, 'BDT': 117.0, 'LKR': 321.5,
    'NPR': 132.5, 'MMK': 2095.0, 'KHR': 4105.0, 'LAK': 21550.0, 'MNT': 3475.0,
    'KZT': 450.5, 'UZS': 12750.0, 'TJS': 10.95, 'KGS': 89.5, 'TMT': 3.5, 'AFN': 71.5,
    'HKD': 7.82, 'TWD': 31.5, 'MOP': 8.07, 'BND': 1.34, 'KPW': 900.0, 'BTN': 83.15,
    'MVR': 15.45, 'NZD': 1.62, 'FJD': 2.23, 'PGK': 3.85, 'SBD': 8.55, 'VUV': 119.5,
    'WST': 2.75, 'TOP': 2.45, 'XPF': 109.5,
}

DEFAULT_USD_GNF_RATE = Decimal('8788.75')
MAX_AMOUNT = Decimal('99999999999999')


def backfill_rate_snapshot(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Budget = apps.get_model('core', 'Budget')
    now = datetime.now(dt_timezone.utc)

    for model, amount_fields in (
        (Project, ('budget', 'budget_consumed')),
        (Budget, ('allocated', 'consumed')),
    ):
        for obj in model.objects.all().iterator():
            changed = False
            if obj.currency not in ('GNF', 'USD'):
                legacy_rate = LEGACY_USD_RATES.get(obj.currency)
                converted = {}
                if legacy_rate:
                    for field in amount_fields:
                        value = float(getattr(obj, field) or 0)
                        result = round(value / legacy_rate * LEGACY_USD_RATES['GNF'], 2)
                        if abs(result) >= float(MAX_AMOUNT):
                            converted = None
                            break
                        converted[field] = Decimal(str(result))
                if converted:
                    for field, value in converted.items():
                        setattr(obj, field, value)
                    obj.currency = 'GNF'
                    changed = True
            if obj.rate_snapshot is None:
                obj.rate_snapshot = DEFAULT_USD_GNF_RATE
                obj.rate_date = now
                changed = True
            if changed:
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_frequency_event_recurrence_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='rate_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du taux figé'),
        ),
        migrations.AddField(
            model_name='budget',
            name='rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Taux figé (GNF pour 1 USD)'),
        ),
        migrations.AddField(
            model_name='project',
            name='rate_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du taux figé'),
        ),
        migrations.AddField(
            model_name='project',
            name='rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Taux figé (GNF pour 1 USD)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('GNF', 'GNF - Franc Guinéen'), ('USD', 'USD - Dollar Américain')], default='GNF', max_length=3, verbose_name='Devise préférée'),
        ),
        migrations.RunPython(backfill_rate_snapshot, migrations.RunPython.noop),
    ]
