# Generated by Django 6.0 on 2026-01-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.projectfolder', verbose_name='Dossier parent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Dossier de projet',
                'verbose_name_plural': 'Dossiers de projet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='project_documents/', verbose_name='Fichier')),
                ('uploaded_by', models.CharField(max_length=100, verbose_name='Uploadé par')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='core.project', verbose_name='Projet')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.projectfolder', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document de projet',
                'verbose_name_plural': 'Documents de projet',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
