# Generated by Django 6.0 on 2026-01-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectfolder_projectdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Responsable'), ('member', 'Membre'), ('observer', 'Observateur')], default='member', max_length=20, verbose_name='Rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='core.employee', verbose_name='Employé')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Membre de projet',
                'verbose_name_plural': 'Membres de projet',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
