# Generated by Django 6.0 on 2026-01-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('created_by', models.CharField(max_length=100, verbose_name='Créé par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Besoin de projet',
                'verbose_name_plural': 'Besoins de projet',
                'ordering': ['-created_at'],
            },
        ),
    ]
