# Generated by Django 6.0 on 2026-01-31 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectneed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Commentaire')),
                ('created_by', models.CharField(max_length=100, verbose_name='Créé par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Commentaire de projet',
                'verbose_name_plural': 'Commentaires de projet',
                'ordering': ['created_at'],
            },
        ),
    ]
