# Generated by Django 6.0 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget_manage',
            field=models.BooleanField(default=False, verbose_name='Peut gérer les budgets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget_view',
            field=models.BooleanField(default=False, verbose_name='Peut voir les budgets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget_view_all_directions',
            field=models.BooleanField(default=False, verbose_name='Peut voir les budgets de toutes les directions'),
        ),
    ]
