# Generated by Django 6.0 on 2026-02-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_more_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_milestones', to='core.employee', verbose_name='Responsable'),
        ),
    ]
