# Generated by Django 6.0 on 2026-02-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_email_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('responsable', 'Responsable'), ('membre', 'Membre'), ('observateur', 'Observateur'), ('personne_ressource', 'Personne ressource'), ('ressource_externe', 'Ressource externe')], default='membre', max_length=20, verbose_name='Rôle'),
        ),
    ]
