# Generated by Django 6.0 on 2026-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_members',
            field=models.BooleanField(default=False, verbose_name='Peut ajouter des membres'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_milestones',
            field=models.BooleanField(default=False, verbose_name='Peut ajouter des jalons'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_requests',
            field=models.BooleanField(default=False, verbose_name='Peut approuver les demandes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_events',
            field=models.BooleanField(default=False, verbose_name='Peut créer des événements'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_project',
            field=models.BooleanField(default=False, verbose_name='Peut créer des projets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_projects',
            field=models.BooleanField(default=False, verbose_name='Peut modifier les projets'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Peut gérer les utilisateurs'),
        ),
    ]
