# Generated by Django 6.0 on 2026-02-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_can_add_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la sous-étape')),
                ('completed', models.BooleanField(default=False, verbose_name='Complétée')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sub_milestones', to='core.employee', verbose_name='Responsable')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_milestones', to='core.milestone', verbose_name='Jalon parent')),
            ],
            options={
                'verbose_name': 'Sous-étape',
                'verbose_name_plural': 'Sous-étapes',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
