# Generated by Django 6.0 on 2026-02-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_submilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('GNF', 'Franc Guinéen (GNF)'), ('USD', 'Dollar US ($)'), ('EUR', 'Euro (€)'), ('GBP', 'Livre Sterling (£)'), ('XOF', 'Franc CFA BCEAO (XOF)'), ('XAF', 'Franc CFA BEAC (XAF)'), ('CNY', 'Yuan Chinois (¥)'), ('JPY', 'Yen Japonais (¥)'), ('CHF', 'Franc Suisse (CHF)'), ('CAD', 'Dollar Canadien (CAD)'), ('AED', 'Dirham Émirats (AED)'), ('SAR', 'Riyal Saoudien (SAR)'), ('MAD', 'Dirham Marocain (MAD)'), ('TND', 'Dinar Tunisien (TND)'), ('NGN', 'Naira Nigérian (NGN)'), ('ZAR', 'Rand Sud-Africain (ZAR)')], default='GNF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('GNF', 'Franc Guinéen (GNF)'), ('USD', 'Dollar US ($)'), ('EUR', 'Euro (€)'), ('GBP', 'Livre Sterling (£)'), ('XOF', 'Franc CFA BCEAO (XOF)'), ('XAF', 'Franc CFA BEAC (XAF)'), ('CNY', 'Yuan Chinois (¥)'), ('JPY', 'Yen Japonais (¥)'), ('CHF', 'Franc Suisse (CHF)'), ('CAD', 'Dollar Canadien (CAD)'), ('AED', 'Dirham Émirats (AED)'), ('SAR', 'Riyal Saoudien (SAR)'), ('MAD', 'Dirham Marocain (MAD)'), ('TND', 'Dinar Tunisien (TND)'), ('NGN', 'Naira Nigérian (NGN)'), ('ZAR', 'Rand Sud-Africain (ZAR)')], default='GNF', max_length=3, verbose_name='Devise'),
        ),
    ]
