# Generated by Django 6.0 on 2026-02-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_currency_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='manual_progress',
            field=models.IntegerField(default=0, verbose_name='Progression manuelle (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='GNF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(default='GNF', max_length=3, verbose_name='Devise'),
        ),
    ]
