# Generated by Django 6.0 on 2026-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_manual_progress_to_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('responsable', 'Responsable'), ('membre', 'Membre'), ('observateur', 'Observateur'), ('personne_ressource', 'Personne ressource'), ('ressource_externe_observateur', 'Ressource externe (observateur)'), ('ressource_externe_edit', 'Ressource externe (éditeur)')], default='membre', max_length=30, verbose_name='Rôle'),
        ),
    ]
