# Generated by Django 6.0 on 2026-02-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_project_member_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('responsable', 'Responsable'), ('membre', 'Membre'), ('observateur', 'Observateur'), ('ressource_externe_observateur', 'Ressource externe (observateur)'), ('ressource_externe_edit', 'Ressource externe (éditeur)')], default='membre', max_length=30, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('ajout_membre', 'Ajout de membre'), ('retrait_membre', 'Retrait de membre'), ('ajout_jalon', 'Ajout de jalon'), ('modif_jalon', 'Modification de jalon'), ('suppr_jalon', 'Suppression de jalon'), ('ajout_sous_etape', 'Ajout de sous-étape'), ('modif_sous_etape', 'Modification de sous-étape'), ('suppr_sous_etape', 'Suppression de sous-étape'), ('toggle_sous_etape', 'Changement statut sous-étape'), ('ajout_document', 'Ajout de document'), ('suppr_document', 'Suppression de document'), ('ajout_dossier', 'Ajout de dossier'), ('suppr_dossier', 'Suppression de dossier'), ('ajout_besoin', 'Ajout de besoin'), ('ajout_commentaire', 'Ajout de commentaire'), ('changement_statut', 'Changement de statut'), ('changement_progression', 'Changement de progression')], max_length=30, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.CharField(max_length=100, verbose_name='Utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Activité de projet',
                'verbose_name_plural': 'Activités de projet',
                'ordering': ['-created_at'],
            },
        ),
    ]
