# Generated by Django 6.0 on 2026-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_project_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Employé'),
        ),
    ]
