# Generated by Django 6.0 on 2026-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_employee_identifier_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Date de fin originale'),
        ),
        migrations.AddField(
            model_name='project',
            name='original_start_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Date de début originale'),
        ),
    ]
