# Generated by Django 6.0 on 2026-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_original_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='can_add_comments_perm',
            field=models.BooleanField(default=False, verbose_name='Ajouter des commentaires'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_add_documents_perm',
            field=models.BooleanField(default=False, verbose_name='Ajouter des documents'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_add_milestones_perm',
            field=models.BooleanField(default=False, verbose_name='Ajouter des jalons'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_add_needs_perm',
            field=models.BooleanField(default=False, verbose_name='Ajouter des besoins'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_edit_project_perm',
            field=models.BooleanField(default=False, verbose_name='Modifier le projet'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_members_perm',
            field=models.BooleanField(default=False, verbose_name='Gérer les membres'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('responsable', 'Responsable'), ('membre', 'Membre'), ('observateur', 'Observateur'), ('ressource_externe_observateur', 'Ressource externe (observateur)'), ('ressource_externe_edit', 'Ressource externe (éditeur)'), ('custom', 'Personnalisé')], default='membre', max_length=30, verbose_name='Rôle'),
        ),
    ]
