# Generated by Django 6.0 on 2026-02-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_projectmember_can_add_comments_perm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='need',
            field=models.TextField(blank=True, default='', verbose_name='Besoin'),
        ),
        migrations.AddField(
            model_name='submilestone',
            name='need',
            field=models.TextField(blank=True, default='', verbose_name='Besoin'),
        ),
    ]
