# Generated by Django 4.2.11 on 2026-05-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_milestone_due_date_submilestone_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.direction', verbose_name='Direction'),
        ),
    ]
