# Generated by Django 4.2.11 on 2026-06-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_leavedocument_id_alter_leaverequest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectneed',
            options={'ordering': ['status', '-created_at'], 'verbose_name': 'Besoin de projet', 'verbose_name_plural': 'Besoins de projet'},
        ),
        migrations.AddField(
            model_name='milestone',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminé le'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('bloque', 'Bloqué'), ('en_revision', 'En révision'), ('termine', 'Terminé')], default='a_faire', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='core.employee', verbose_name='Responsable (lié)'),
        ),
        migrations.AddField(
            model_name='projectneed',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AddField(
            model_name='projectneed',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Traité par'),
        ),
        migrations.AddField(
            model_name='projectneed',
            name='status',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='ouvert', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='submilestone',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminée le'),
        ),
    ]
