# Generated by Django 4.2.11 on 2026-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sync_milestone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('en_retard', 'En retard')], default='planifie', max_length=20, verbose_name='Statut'),
        ),
        migrations.RemoveField(
            model_name='submilestone',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='milestone',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_milestones', to='core.employee', verbose_name='Responsables'),
        ),
        migrations.AddField(
            model_name='submilestone',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_sub_milestones', to='core.employee', verbose_name='Responsables'),
        ),
    ]
