# Generated by Django 4.2.11 on 2026-06-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_m2m_milestone_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Personne externe'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, max_length=150, verbose_name='Organisation / Entreprise'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.direction', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Rôle / Fonction'),
        ),
    ]
