# Generated by Django 4.2.11 on 2026-06-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_employee_external_nullable_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.employee', unique=True, verbose_name='Employé'),
        ),
    ]
