# Generated by Django 4.2.11 on 2026-06-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_harmonize_userprofile_employee_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.employee', verbose_name='Employé'),
        ),
    ]
