# Generated by Django 5.2 — Migration RBAC

from django.db import migrations, models
import django.db.models.deletion


def save_old_roles(apps, schema_editor):
    """Copie l'ancien role (CharField) vers _role_legacy avant qu'il soit supprimé."""
    schema_editor.execute(
        "UPDATE core_userprofile SET _role_legacy = role WHERE role IS NOT NULL"
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_employee_fk_to_onetoonefield'),
    ]

    operations = [
        # --- Nouvelles tables RBAC ---
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read', 'Lire'), ('create', 'Créer'), ('update', 'Modifier'), ('delete', 'Supprimer'), ('manage', 'Gérer (tout)'), ('approve', 'Approuver'), ('export', 'Exporter')], max_length=20, verbose_name='Action')),
                ('subject', models.CharField(choices=[('all', 'Tout'), ('Project', 'Projets'), ('Milestone', 'Jalons / Tâches'), ('Budget', 'Budgets'), ('User', 'Utilisateurs'), ('Employee', 'Employés'), ('LeaveRequest', 'Demandes de congé'), ('Partner', 'Partenaires'), ('Document', 'Documents'), ('Request', 'Demandes'), ('Event', 'Événements'), ('Direction', 'Directions'), ('Role', 'Rôles'), ('Report', 'Rapports')], max_length=30, verbose_name='Sujet')),
                ('condition', models.CharField(blank=True, choices=[('', 'Aucune (accès global)'), ('same_direction', 'Même direction'), ('is_project_manager', 'Est manager du projet'), ('is_project_member', 'Est membre du projet'), ('is_owner', 'Est propriétaire'), ('hr_pipeline', 'Pipeline RH (après avis hiérarchique)')], default='', max_length=30, verbose_name='Condition')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['subject', 'action'],
                'unique_together': {('action', 'subject', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system', models.BooleanField(default=False, verbose_name='Rôle système (non supprimable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system', models.BooleanField(default=False, verbose_name='Rôle système (non supprimable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='project_roles', to='core.permission', verbose_name='Permissions projet')),
            ],
            options={
                'verbose_name': 'Rôle projet',
                'verbose_name_plural': 'Rôles projet',
                'ordering': ['name'],
            },
        ),

        # --- Nettoyage ProjectMember ---
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['joined_at'], 'verbose_name': 'Membre de projet', 'verbose_name_plural': 'Membres de projet'},
        ),
        migrations.RemoveField(model_name='projectmember', name='can_add_comments_perm'),
        migrations.RemoveField(model_name='projectmember', name='can_add_documents_perm'),
        migrations.RemoveField(model_name='projectmember', name='can_add_milestones_perm'),
        migrations.RemoveField(model_name='projectmember', name='can_add_needs_perm'),
        migrations.RemoveField(model_name='projectmember', name='can_edit_project_perm'),
        migrations.RemoveField(model_name='projectmember', name='can_manage_members_perm'),
        migrations.RemoveField(model_name='projectmember', name='role'),
        migrations.AddField(
            model_name='projectmember',
            name='project_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.projectrole', verbose_name='Rôle projet'),
        ),

        # --- Nettoyage UserProfile : booléens ---
        migrations.RemoveField(model_name='userprofile', name='budget_manage'),
        migrations.RemoveField(model_name='userprofile', name='budget_view'),
        migrations.RemoveField(model_name='userprofile', name='budget_view_all_directions'),
        migrations.RemoveField(model_name='userprofile', name='can_add_members'),
        migrations.RemoveField(model_name='userprofile', name='can_add_milestones'),
        migrations.RemoveField(model_name='userprofile', name='can_approve_leaves'),
        migrations.RemoveField(model_name='userprofile', name='can_approve_requests'),
        migrations.RemoveField(model_name='userprofile', name='can_create_events'),
        migrations.RemoveField(model_name='userprofile', name='can_create_project'),
        migrations.RemoveField(model_name='userprofile', name='can_edit_projects'),
        migrations.RemoveField(model_name='userprofile', name='can_manage_users'),
        migrations.RemoveField(model_name='userprofile', name='is_hr_manager'),

        # --- Sauvegarde de l'ancien role CharField dans _role_legacy ---
        # Étape 1 : ajouter la colonne temporaire
        migrations.AddField(
            model_name='userprofile',
            name='_role_legacy',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        # Étape 2 : copier les valeurs (SQL direct car RunPython ne peut pas
        # lire le champ 'role' après qu'il a été supprimé dans la même migration)
        migrations.RunPython(save_old_roles, noop),

        # Étape 3 : supprimer l'ancien CharField puis ajouter le FK nullable
        # (split RemoveField + AddField obligatoire sur SQLite pour éviter l'erreur
        # FK integrity lors de la reconstruction de la table)
        migrations.RemoveField(model_name='userprofile', name='role'),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.role', verbose_name='Rôle'),
        ),
    ]
