# Generated by Django 5.2.15 on 2026-06-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rbac_add_update_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='subject',
            field=models.CharField(choices=[('all', 'Tout'), ('Project', 'Projets'), ('Milestone', 'Jalons / Tâches'), ('Comment', 'Commentaires projet'), ('ProjectMember', 'Membres de projet'), ('Budget', 'Budgets'), ('User', 'Utilisateurs'), ('Employee', 'Employés'), ('LeaveRequest', 'Demandes de congé'), ('Partner', 'Partenaires'), ('Document', 'Documents'), ('Request', 'Demandes / Besoins projet'), ('Event', 'Événements'), ('Direction', 'Directions'), ('Role', 'Rôles'), ('Report', 'Rapports')], max_length=30, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('ajout_membre', 'Ajout de membre'), ('retrait_membre', 'Retrait de membre'), ('ajout_jalon', 'Ajout de jalon'), ('modif_jalon', 'Modification de jalon'), ('suppr_jalon', 'Suppression de jalon'), ('ajout_sous_etape', 'Ajout de sous-étape'), ('modif_sous_etape', 'Modification de sous-étape'), ('suppr_sous_etape', 'Suppression de sous-étape'), ('toggle_jalon', 'Changement statut jalon'), ('modif_statut_jalon', 'Modification statut jalon'), ('toggle_sous_etape', 'Changement statut sous-étape'), ('ajout_document', 'Ajout de document'), ('suppr_document', 'Suppression de document'), ('ajout_dossier', 'Ajout de dossier'), ('suppr_dossier', 'Suppression de dossier'), ('ajout_besoin', 'Ajout de besoin'), ('ajout_commentaire', 'Ajout de commentaire'), ('changement_statut', 'Changement de statut'), ('changement_progression', 'Changement de progression')], max_length=30, verbose_name='Action'),
        ),
    ]
