# Generated by Django 4.2.11 on 2026-06-24 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0040_alter_permission_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('jalon_complete', 'Jalon complété'), ('sous_etape_complete', 'Sous-étape complétée'), ('membre_projet', 'Ajout comme membre de projet'), ('commentaire', 'Nouveau commentaire'), ('conge_avis', 'Avis hiérarchique congé'), ('conge_rh', 'Vérification RH congé'), ('conge_decision', 'Décision finale congé')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
