# Generated by Django 4.2.11 on 2026-06-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('jalon_complete', 'Jalon complété'), ('sous_etape_complete', 'Sous-étape complétée'), ('membre_projet', 'Ajout comme membre de projet'), ('commentaire', 'Nouveau commentaire'), ('conge_avis', 'Avis hiérarchique congé'), ('conge_rh', 'Vérification RH congé'), ('conge_decision', 'Décision finale congé'), ('event_invite', 'Invitation à un événement'), ('event_update', 'Événement modifié'), ('event_cancel', 'Événement annulé'), ('event_rsvp', 'Réponse à une invitation')], max_length=30, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invite', 'Invité'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('peut_etre', 'Peut-être')], default='invite', max_length=20, verbose_name='Statut RSVP')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invité le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to='core.employee', verbose_name='Employé')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='core.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Membre d'événement",
                'verbose_name_plural': "Membres d'événement",
                'ordering': ['employee__name'],
                'unique_together': {('event', 'employee')},
            },
        ),
    ]
