# Generated by Django 4.2.11 on 2026-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_event_member_and_notif_types'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventmember',
            index=models.Index(fields=['event', 'status'], name='core_eventm_event_i_f54c7a_idx'),
        ),
    ]
