# Generated by Django 4.2.11 on 2026-06-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_eventmember_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('reunion', 'Réunion'), ('evenement', 'Événement')], max_length=20, verbose_name='Type'),
        ),
    ]
