# Generated by Django 4.2.11 on 2026-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_deadline_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('a_signer', 'À signer'), ('a_valider', 'À valider'), ('signe', 'Signé')], db_index=True, default='a_valider', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('soumise', 'Soumise - en attente avis hiérarchique'), ('avis_favorable', 'Avis hiérarchique favorable - en attente RH'), ('avis_defavorable', 'Avis hiérarchique défavorable'), ('rh_conforme', 'Vérifiée RH - en attente décision finale'), ('rh_non_conforme', 'Non conforme RH'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée par le demandeur')], db_index=True, default='soumise', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('en_discussion', 'En discussion'), ('inactif', 'Inactif')], db_index=True, default='en_discussion', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('en_retard', 'En retard')], db_index=True, default='planifie', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'is_read'], name='notif_receiver_read_idx'),
        ),
    ]
