# Generated by Django 4.2.11 on 2026-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_perf_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='leavedocument',
            name='file',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='justification',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Justificatif'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Photo'),
        ),
    ]
