# Generated by Django 4.2.11 on 2026-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_convert_file_fields_to_urlfield_for_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='description_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Contexte description'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('activate', 'Activation'), ('view', 'Consultation')], max_length=20, verbose_name='Action'),
        ),
    ]
