# Generated by Django 4.2.11 on 2026-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_useractivity_description_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='description_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Contexte description'),
        ),
    ]
