# Liste complète des devises du monde
CURRENCY_CHOICES = [
    # Afrique
    ('GNF', 'GNF - Franc Guinéen'),
    ('XOF', 'XOF - Franc CFA BCEAO'),
    ('XAF', 'XAF - Franc CFA BEAC'),
    ('NGN', 'NGN - Naira Nigérian'),
    ('ZAR', 'ZAR - Rand Sud-Africain'),
    ('EGP', 'EGP - Livre Égyptienne'),
    ('MAD', 'MAD - Dirham Marocain'),
    ('TND', 'TND - Dinar Tunisien'),
    ('DZD', 'DZD - Dinar Algérien'),
    ('KES', 'KES - Shilling Kényan'),
    ('GHS', 'GHS - Cedi Ghanéen'),
    ('ETB', 'ETB - Birr Éthiopien'),
    ('TZS', 'TZS - Shilling Tanzanien'),
    ('UGX', 'UGX - Shilling Ougandais'),
    ('RWF', 'RWF - Franc Rwandais'),
    ('MUR', 'MUR - Roupie Mauricienne'),
    ('SLL', 'SLL - Leone Sierra-Léonais'),
    ('LRD', 'LRD - Dollar Libérien'),
    ('GMD', 'GMD - Dalasi Gambien'),
    ('CVE', 'CVE - Escudo Cap-Verdien'),
    ('MZN', 'MZN - Metical Mozambicain'),
    ('AOA', 'AOA - Kwanza Angolais'),
    ('ZMW', 'ZMW - Kwacha Zambien'),
    ('BWP', 'BWP - Pula Botswanais'),
    ('NAD', 'NAD - Dollar Namibien'),
    ('SZL', 'SZL - Lilangeni Swazi'),
    ('LSL', 'LSL - Loti Lesothan'),
    ('MWK', 'MWK - Kwacha Malawite'),
    ('ZWL', 'ZWL - Dollar Zimbabwéen'),
    ('SDG', 'SDG - Livre Soudanaise'),
    ('LYD', 'LYD - Dinar Libyen'),
    ('MRU', 'MRU - Ouguiya Mauritanien'),
    ('SCR', 'SCR - Roupie Seychelloise'),
    ('DJF', 'DJF - Franc Djiboutien'),
    ('KMF', 'KMF - Franc Comorien'),
    ('ERN', 'ERN - Nakfa Érythréen'),
    ('SOS', 'SOS - Shilling Somalien'),
    ('SSP', 'SSP - Livre Sud-Soudanaise'),
    ('STN', 'STN - Dobra Santoméen'),
    ('BIF', 'BIF - Franc Burundais'),
    ('CDF', 'CDF - Franc Congolais'),
    ('MGA', 'MGA - Ariary Malgache'),
    
    # Amérique du Nord
    ('USD', 'USD - Dollar Américain'),
    ('CAD', 'CAD - Dollar Canadien'),
    ('MXN', 'MXN - Peso Mexicain'),
    
    # Amérique Centrale et Caraïbes
    ('GTQ', 'GTQ - Quetzal Guatémaltèque'),
    ('HNL', 'HNL - Lempira Hondurien'),
    ('NIO', 'NIO - Córdoba Nicaraguayen'),
    ('CRC', 'CRC - Colón Costaricain'),
    ('PAB', 'PAB - Balboa Panaméen'),
    ('DOP', 'DOP - Peso Dominicain'),
    ('CUP', 'CUP - Peso Cubain'),
    ('JMD', 'JMD - Dollar Jamaïcain'),
    ('HTG', 'HTG - Gourde Haïtienne'),
    ('TTD', 'TTD - Dollar Trinidadien'),
    ('BBD', 'BBD - Dollar Barbadien'),
    ('BSD', 'BSD - Dollar Bahaméen'),
    ('BZD', 'BZD - Dollar Bélizien'),
    ('XCD', 'XCD - Dollar des Caraïbes Orientales'),
    ('AWG', 'AWG - Florin Arubais'),
    ('ANG', 'ANG - Florin Antillais'),
    ('KYD', 'KYD - Dollar des Îles Caïmans'),
    
    # Amérique du Sud
    ('BRL', 'BRL - Réal Brésilien'),
    ('ARS', 'ARS - Peso Argentin'),
    ('CLP', 'CLP - Peso Chilien'),
    ('COP', 'COP - Peso Colombien'),
    ('PEN', 'PEN - Sol Péruvien'),
    ('VES', 'VES - Bolívar Vénézuélien'),
    ('UYU', 'UYU - Peso Uruguayen'),
    ('PYG', 'PYG - Guaraní Paraguayen'),
    ('BOB', 'BOB - Boliviano'),
    ('GYD', 'GYD - Dollar Guyanien'),
    ('SRD', 'SRD - Dollar Surinamais'),
    ('FKP', 'FKP - Livre des Malouines'),
    
    # Europe
    ('EUR', 'EUR - Euro'),
    ('GBP', 'GBP - Livre Sterling'),
    ('CHF', 'CHF - Franc Suisse'),
    ('NOK', 'NOK - Couronne Norvégienne'),
    ('SEK', 'SEK - Couronne Suédoise'),
    ('DKK', 'DKK - Couronne Danoise'),
    ('PLN', 'PLN - Zloty Polonais'),
    ('CZK', 'CZK - Couronne Tchèque'),
    ('HUF', 'HUF - Forint Hongrois'),
    ('RON', 'RON - Leu Roumain'),
    ('BGN', 'BGN - Lev Bulgare'),
    ('HRK', 'HRK - Kuna Croate'),
    ('RSD', 'RSD - Dinar Serbe'),
    ('UAH', 'UAH - Hryvnia Ukrainienne'),
    ('RUB', 'RUB - Rouble Russe'),
    ('BYN', 'BYN - Rouble Biélorusse'),
    ('MDL', 'MDL - Leu Moldave'),
    ('ALL', 'ALL - Lek Albanais'),
    ('MKD', 'MKD - Denar Macédonien'),
    ('BAM', 'BAM - Mark Convertible'),
    ('ISK', 'ISK - Couronne Islandaise'),
    ('TRY', 'TRY - Livre Turque'),
    ('GEL', 'GEL - Lari Géorgien'),
    ('AMD', 'AMD - Dram Arménien'),
    ('AZN', 'AZN - Manat Azerbaïdjanais'),
    
    # Moyen-Orient
    ('AED', 'AED - Dirham Émirats'),
    ('SAR', 'SAR - Riyal Saoudien'),
    ('QAR', 'QAR - Riyal Qatari'),
    ('KWD', 'KWD - Dinar Koweïtien'),
    ('BHD', 'BHD - Dinar Bahreïni'),
    ('OMR', 'OMR - Rial Omanais'),
    ('JOD', 'JOD - Dinar Jordanien'),
    ('LBP', 'LBP - Livre Libanaise'),
    ('SYP', 'SYP - Livre Syrienne'),
    ('IQD', 'IQD - Dinar Irakien'),
    ('IRR', 'IRR - Rial Iranien'),
    ('YER', 'YER - Rial Yéménite'),
    ('ILS', 'ILS - Shekel Israélien'),
    
    # Asie
    ('CNY', 'CNY - Yuan Chinois'),
    ('JPY', 'JPY - Yen Japonais'),
    ('KRW', 'KRW - Won Sud-Coréen'),
    ('INR', 'INR - Roupie Indienne'),
    ('IDR', 'IDR - Roupie Indonésienne'),
    ('MYR', 'MYR - Ringgit Malaisien'),
    ('SGD', 'SGD - Dollar Singapourien'),
    ('THB', 'THB - Baht Thaïlandais'),
    ('VND', 'VND - Dong Vietnamien'),
    ('PHP', 'PHP - Peso Philippin'),
    ('PKR', 'PKR - Roupie Pakistanaise'),
    ('BDT', 'BDT - Taka Bangladais'),
    ('LKR', 'LKR - Roupie Sri-Lankaise'),
    ('NPR', 'NPR - Roupie Népalaise'),
    ('MMK', 'MMK - Kyat Birman'),
    ('KHR', 'KHR - Riel Cambodgien'),
    ('LAK', 'LAK - Kip Laotien'),
    ('MNT', 'MNT - Tugrik Mongol'),
    ('KZT', 'KZT - Tenge Kazakh'),
    ('UZS', 'UZS - Sum Ouzbek'),
    ('TJS', 'TJS - Somoni Tadjik'),
    ('KGS', 'KGS - Som Kirghiz'),
    ('TMT', 'TMT - Manat Turkmène'),
    ('AFN', 'AFN - Afghani'),
    ('HKD', 'HKD - Dollar Hong-Kongais'),
    ('TWD', 'TWD - Dollar Taïwanais'),
    ('MOP', 'MOP - Pataca Macanaise'),
    ('BND', 'BND - Dollar Brunéien'),
    ('KPW', 'KPW - Won Nord-Coréen'),
    ('BTN', 'BTN - Ngultrum Bhoutanais'),
    ('MVR', 'MVR - Rufiyaa Maldivienne'),
    
    # Océanie
    ('AUD', 'AUD - Dollar Australien'),
    ('NZD', 'NZD - Dollar Néo-Zélandais'),
    ('FJD', 'FJD - Dollar Fidjien'),
    ('PGK', 'PGK - Kina Papou'),
    ('SBD', 'SBD - Dollar des Îles Salomon'),
    ('VUV', 'VUV - Vatu Vanuatais'),
    ('WST', 'WST - Tala Samoan'),
    ('TOP', 'TOP - Pa\'anga Tongan'),
    ('XPF', 'XPF - Franc CFP'),
]

# Taux de change par rapport à l'USD (taux approximatifs pour 2024)
EXCHANGE_RATES = {
    # Devises principales
    'USD': 1.0,
    'EUR': 0.92,
    'GBP': 0.79,
    'JPY': 149.50,
    'CNY': 7.24,
    'CAD': 1.36,
    'AUD': 1.53,
    'CHF': 0.88,
    
    # Afrique
    'GNF': 8655.0,
    'XOF': 606.0,
    'XAF': 606.0,
    'NGN': 772.0,
    'ZAR': 18.85,
    'EGP': 31.0,
    'MAD': 10.05,
    'TND': 3.12,
    'DZD': 136.5,
    'KES': 151.5,
    'GHS': 12.15,
    'ETB': 56.5,
    'TZS': 2475.0,
    'UGX': 3765.0,
    'RWF': 1315.0,
    'MUR': 45.5,
    'SLL': 22775.0,
    'LRD': 191.5,
    'GMD': 64.5,
    'CVE': 102.5,
    'MZN': 64.05,
    'AOA': 826.5,
    'ZMW': 24.85,
    'BWP': 13.55,
    'NAD': 18.85,
    'SZL': 18.85,
    'LSL': 18.85,
    'MWK': 1735.0,
    'ZWL': 3619.0,
    'SDG': 602.5,
    'LYD': 4.86,
    'MRU': 39.5,
    'SCR': 45.5,
    'DJF': 177.5,
    'KMF': 453.0,
    'ERN': 15.0,
    'SOS': 570.0,
    'SSP': 185.5,
    'STN': 22.65,
    'BIF': 2855.0,
    'CDF': 2725.0,
    'MGA': 4565.0,
    
    # Amérique
    'MXN': 17.15,
    'GTQ': 7.82,
    'HNL': 24.65,
    'NIO': 36.85,
    'CRC': 543.5,
    'PAB': 1.0,
    'DOP': 56.85,
    'CUP': 24.0,
    'JMD': 155.5,
    'HTG': 132.5,
    'TTD': 6.75,
    'BBD': 2.0,
    'BSD': 1.0,
    'BZD': 2.0,
    'XCD': 2.7,
    'AWG': 1.8,
    'ANG': 1.79,
    'KYD': 0.83,
    'BRL': 4.95,
    'ARS': 835.5,
    'CLP': 915.5,
    'COP': 3925.0,
    'PEN': 3.75,
    'VES': 3619250.0,
    'UYU': 38.85,
    'PYG': 7325.0,
    'BOB': 6.95,
    'GYD': 209.5,
    'SRD': 34.65,
    'FKP': 0.79,
    
    # Europe
    'NOK': 10.65,
    'SEK': 10.85,
    'DKK': 6.85,
    'PLN': 3.95,
    'CZK': 22.85,
    'HUF': 355.5,
    'RON': 4.62,
    'BGN': 1.8,
    'HRK': 7.15,
    'RSD': 107.5,
    'UAH': 39.15,
    'RUB': 89.5,
    'BYN': 3.25,
    'MDL': 17.85,
    'ALL': 94.5,
    'MKD': 56.5,
    'BAM': 1.8,
    'ISK': 137.5,
    'TRY': 31.5,
    'GEL': 2.75,
    'AMD': 387.5,
    'AZN': 1.7,
    
    # Moyen-Orient
    'AED': 3.67,
    'SAR': 3.75,
    'QAR': 3.64,
    'KWD': 0.31,
    'BHD': 0.38,
    'OMR': 0.38,
    'JOD': 0.71,
    'LBP': 89500.0,
    'SYP': 12950.0,
    'IQD': 1315.0,
    'IRR': 42250.0,
    'YER': 250.5,
    'ILS': 3.65,
    
    # Asie
    'KRW': 1315.0,
    'INR': 83.15,
    'IDR': 15650.0,
    'MYR': 4.65,
    'SGD': 1.34,
    'THB': 35.85,
    'VND': 24450.0,
    'PHP': 56.5,
    'PKR': 279.5,
    'BDT': 117.0,
    'LKR': 321.5,
    'NPR': 132.5,
    'MMK': 2095.0,
    'KHR': 4105.0,
    'LAK': 21550.0,
    'MNT': 3475.0,
    'KZT': 450.5,
    'UZS': 12750.0,
    'TJS': 10.95,
    'KGS': 89.5,
    'TMT': 3.5,
    'AFN': 71.5,
    'HKD': 7.82,
    'TWD': 31.5,
    'MOP': 8.07,
    'BND': 1.34,
    'KPW': 900.0,
    'BTN': 83.15,
    'MVR': 15.45,
    
    # Océanie
    'NZD': 1.62,
    'FJD': 2.23,
    'PGK': 3.85,
    'SBD': 8.55,
    'VUV': 119.5,
    'WST': 2.75,
    'TOP': 2.45,
    'XPF': 109.5,
}

def convert_currency(amount, from_currency, to_currency):
    """Convertit un montant d'une devise à une autre"""
    if from_currency == to_currency:
        return amount
    
    # Convertir d'abord en USD si nécessaire
    if from_currency != 'USD':
        amount_in_usd = amount / EXCHANGE_RATES.get(from_currency, 1.0)
    else:
        amount_in_usd = amount
    
    # Puis convertir vers la devise cible
    if to_currency != 'USD':
        converted_amount = amount_in_usd * EXCHANGE_RATES.get(to_currency, 1.0)
    else:
        converted_amount = amount_in_usd
    
    return round(converted_amount, 2)

def format_currency(amount, currency):
    """Formate un montant selon la devise"""
    if currency in ['JPY', 'KRW', 'VND', 'CLP', 'COP', 'PYG', 'UGX', 'RWF', 'BIF', 'CDF', 'MGA', 'GNF', 'XOF', 'XAF']:
        # Devises sans décimales
        return f"{int(amount):,} {currency}"
    else:
        # Devises avec 2 décimales
        return f"{amount:,.2f} {currency}"
