# Liste complète des devises du monde
CURRENCY_CHOICES = [
    # Afrique
    ('GNF', 'GNF - Franc Guinéen'),
    ('XOF', 'XOF - Franc CFA BCEAO'),
    ('XAF', 'XAF - Franc CFA BEAC'),
    ('NGN', 'NGN - Naira Nigérian'),
    ('ZAR', 'ZAR - Rand Sud-Africain'),
    ('EGP', 'EGP - Livre Égyptienne'),
    ('MAD', 'MAD - Dirham Marocain'),
    ('TND', 'TND - Dinar Tunisien'),
    ('DZD', 'DZD - Dinar Algérien'),
    ('KES', 'KES - Shilling Kényan'),
    ('GHS', 'GHS - Cedi Ghanéen'),
    ('ETB', 'ETB - Birr Éthiopien'),
    ('TZS', 'TZS - Shilling Tanzanien'),
    ('UGX', 'UGX - Shilling Ougandais'),
    ('RWF', 'RWF - Franc Rwandais'),
    ('MUR', 'MUR - Roupie Mauricienne'),
    ('SLL', 'SLL - Leone Sierra-Léonais'),
    ('LRD', 'LRD - Dollar Libérien'),
    ('GMD', 'GMD - Dalasi Gambien'),
    ('CVE', 'CVE - Escudo Cap-Verdien'),
    ('MZN', 'MZN - Metical Mozambicain'),
    ('AOA', 'AOA - Kwanza Angolais'),
    ('ZMW', 'ZMW - Kwacha Zambien'),
    ('BWP', 'BWP - Pula Botswanais'),
    ('NAD', 'NAD - Dollar Namibien'),
    ('SZL', 'SZL - Lilangeni Swazi'),
    ('LSL', 'LSL - Loti Lesothan'),
    ('MWK', 'MWK - Kwacha Malawite'),
    ('ZWL', 'ZWL - Dollar Zimbabwéen'),
    ('SDG', 'SDG - Livre Soudanaise'),
    ('LYD', 'LYD - Dinar Libyen'),
    ('MRU', 'MRU - Ouguiya Mauritanien'),
    ('SCR', 'SCR - Roupie Seychelloise'),
    ('DJF', 'DJF - Franc Djiboutien'),
    ('KMF', 'KMF - Franc Comorien'),
    ('ERN', 'ERN - Nakfa Érythréen'),
    ('SOS', 'SOS - Shilling Somalien'),
    ('SSP', 'SSP - Livre Sud-Soudanaise'),
    ('STN', 'STN - Dobra Santoméen'),
    ('BIF', 'BIF - Franc Burundais'),
    ('CDF', 'CDF - Franc Congolais'),
    ('MGA', 'MGA - Ariary Malgache'),
    
    # Amérique du Nord
    ('USD', 'USD - Dollar Américain'),
    ('CAD', 'CAD - Dollar Canadien'),
    ('MXN', 'MXN - Peso Mexicain'),
    
    # Amérique Centrale et Caraïbes
    ('GTQ', 'GTQ - Quetzal Guatémaltèque'),
    ('HNL', 'HNL - Lempira Hondurien'),
    ('NIO', 'NIO - Córdoba Nicaraguayen'),
    ('CRC', 'CRC - Colón Costaricain'),
    ('PAB', 'PAB - Balboa Panaméen'),
    ('DOP', 'DOP - Peso Dominicain'),
    ('CUP', 'CUP - Peso Cubain'),
    ('JMD', 'JMD - Dollar Jamaïcain'),
    ('HTG', 'HTG - Gourde Haïtienne'),
    ('TTD', 'TTD - Dollar Trinidadien'),
    ('BBD', 'BBD - Dollar Barbadien'),
    ('BSD', 'BSD - Dollar Bahaméen'),
    ('BZD', 'BZD - Dollar Bélizien'),
    ('XCD', 'XCD - Dollar des Caraïbes Orientales'),
    ('AWG', 'AWG - Florin Arubais'),
    ('ANG', 'ANG - Florin Antillais'),
    ('KYD', 'KYD - Dollar des Îles Caïmans'),
    
    # Amérique du Sud
    ('BRL', 'BRL - Réal Brésilien'),
    ('ARS', 'ARS - Peso Argentin'),
    ('CLP', 'CLP - Peso Chilien'),
    ('COP', 'COP - Peso Colombien'),
    ('PEN', 'PEN - Sol Péruvien'),
    ('VES', 'VES - Bolívar Vénézuélien'),
    ('UYU', 'UYU - Peso Uruguayen'),
    ('PYG', 'PYG - Guaraní Paraguayen'),
    ('BOB', 'BOB - Boliviano'),
    ('GYD', 'GYD - Dollar Guyanien'),
    ('SRD', 'SRD - Dollar Surinamais'),
    ('FKP', 'FKP - Livre des Malouines'),
    
    # Europe
    ('EUR', 'EUR - Euro'),
    ('GBP', 'GBP - Livre Sterling'),
    ('CHF', 'CHF - Franc Suisse'),
    ('NOK', 'NOK - Couronne Norvégienne'),
    ('SEK', 'SEK - Couronne Suédoise'),
    ('DKK', 'DKK - Couronne Danoise'),
    ('PLN', 'PLN - Zloty Polonais'),
    ('CZK', 'CZK - Couronne Tchèque'),
    ('HUF', 'HUF - Forint Hongrois'),
    ('RON', 'RON - Leu Roumain'),
    ('BGN', 'BGN - Lev Bulgare'),
    ('HRK', 'HRK - Kuna Croate'),
    ('RSD', 'RSD - Dinar Serbe'),
    ('UAH', 'UAH - Hryvnia Ukrainienne'),
    ('RUB', 'RUB - Rouble Russe'),
    ('BYN', 'BYN - Rouble Biélorusse'),
    ('MDL', 'MDL - Leu Moldave'),
    ('ALL', 'ALL - Lek Albanais'),
    ('MKD', 'MKD - Denar Macédonien'),
    ('BAM', 'BAM - Mark Convertible'),
    ('ISK', 'ISK - Couronne Islandaise'),
    ('TRY', 'TRY - Livre Turque'),
    ('GEL', 'GEL - Lari Géorgien'),
    ('AMD', 'AMD - Dram Arménien'),
    ('AZN', 'AZN - Manat Azerbaïdjanais'),
    
    # Moyen-Orient
    ('AED', 'AED - Dirham Émirats'),
    ('SAR', 'SAR - Riyal Saoudien'),
    ('QAR', 'QAR - Riyal Qatari'),
    ('KWD', 'KWD - Dinar Koweïtien'),
    ('BHD', 'BHD - Dinar Bahreïni'),
    ('OMR', 'OMR - Rial Omanais'),
    ('JOD', 'JOD - Dinar Jordanien'),
    ('LBP', 'LBP - Livre Libanaise'),
    ('SYP', 'SYP - Livre Syrienne'),
    ('IQD', 'IQD - Dinar Irakien'),
    ('IRR', 'IRR - Rial Iranien'),
    ('YER', 'YER - Rial Yéménite'),
    ('ILS', 'ILS - Shekel Israélien'),
    
    # Asie
    ('CNY', 'CNY - Yuan Chinois'),
    ('JPY', 'JPY - Yen Japonais'),
    ('KRW', 'KRW - Won Sud-Coréen'),
    ('INR', 'INR - Roupie Indienne'),
    ('IDR', 'IDR - Roupie Indonésienne'),
    ('MYR', 'MYR - Ringgit Malaisien'),
    ('SGD', 'SGD - Dollar Singapourien'),
    ('THB', 'THB - Baht Thaïlandais'),
    ('VND', 'VND - Dong Vietnamien'),
    ('PHP', 'PHP - Peso Philippin'),
    ('PKR', 'PKR - Roupie Pakistanaise'),
    ('BDT', 'BDT - Taka Bangladais'),
    ('LKR', 'LKR - Roupie Sri-Lankaise'),
    ('NPR', 'NPR - Roupie Népalaise'),
    ('MMK', 'MMK - Kyat Birman'),
    ('KHR', 'KHR - Riel Cambodgien'),
    ('LAK', 'LAK - Kip Laotien'),
    ('MNT', 'MNT - Tugrik Mongol'),
    ('KZT', 'KZT - Tenge Kazakh'),
    ('UZS', 'UZS - Sum Ouzbek'),
    ('TJS', 'TJS - Somoni Tadjik'),
    ('KGS', 'KGS - Som Kirghiz'),
    ('TMT', 'TMT - Manat Turkmène'),
    ('AFN', 'AFN - Afghani'),
    ('HKD', 'HKD - Dollar Hong-Kongais'),
    ('TWD', 'TWD - Dollar Taïwanais'),
    ('MOP', 'MOP - Pataca Macanaise'),
    ('BND', 'BND - Dollar Brunéien'),
    ('KPW', 'KPW - Won Nord-Coréen'),
    ('BTN', 'BTN - Ngultrum Bhoutanais'),
    ('MVR', 'MVR - Rufiyaa Maldivienne'),
    
    # Océanie
    ('AUD', 'AUD - Dollar Australien'),
    ('NZD', 'NZD - Dollar Néo-Zélandais'),
    ('FJD', 'FJD - Dollar Fidjien'),
    ('PGK', 'PGK - Kina Papou'),
    ('SBD', 'SBD - Dollar des Îles Salomon'),
    ('VUV', 'VUV - Vatu Vanuatais'),
    ('WST', 'WST - Tala Samoan'),
    ('TOP', 'TOP - Pa\'anga Tongan'),
    ('XPF', 'XPF - Franc CFP'),
]
